WALimaRoomsV3.5-f82c69496623d605ed5b4bd9917f5774eca0c520/WALimaRoomsV3.5/Controllers/TipoDocumentoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Business;
using Business.Implementacion;
using Entity;

namespace WALimaRoomsV3._5.Controllers
{
    public class TipoDocumentoController : Controller
    {
        ITipoDocumentoService TipoServ = new TipoDocumentoService();
        
        // GET: TipoDocumento
        public ActionResult Index()
        {
            return View(TipoServ.FindAll());
        }

        // GET: TipoDocumento/Details/5
        public ActionResult Details(int id)
        {
            return View(TipoServ.FindById(id));
        }

        // GET: TipoDocumento/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: TipoDocumento/Create
        [HttpPost]
        public ActionResult Create(TipoDocumento collection)
        {
            bool rpta = TipoServ.insert(collection);

            if (rpta)
            {
                return RedirectToAction("Index");
            }

            return View();
        }

        // GET: TipoDocumento/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }


            TipoDocumento TipoD = TipoServ.FindById(id);

            return View(TipoD);
        }

        // POST: TipoDocumento/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, TipoDocumento collection)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            bool rpta = TipoServ.Update(collection);

            if (rpta)
            {
                return RedirectToAction("Index");
            }
            return View();
        }

        // GET: TipoDocumento/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            TipoDocumento TipoD = TipoServ.FindById(id);

            return View(TipoD);
        }

        // POST: TipoDocumento/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, TipoDocumento collection)
        {
            bool rpta = TipoServ.Delete(collection.TipoDocumentoId);

            if (rpta)
            {
                return RedirectToAction("Index");
            }
            return View();

        }
    }
}

WALimaRoomsV3.5-f82c69496623d605ed5b4bd9917f5774eca0c520/WALimaRoomsV3.5/Controllers/TipoInmobiliarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Entity;
using Business;
using Business.Implementacion;
namespace WALimaRoomsV3._5.Controllers
{
    public class TipoInmobiliarioController : Controller
    {
        private ITipoInmobiliarioService TipoServ = new TipoInmobiliarioService();
        private IInmobiliarioService inmobiliarioServ = new InmobiliarioService();
        // GET: TipoInmobiliario
        public ActionResult Index()
        {
            return View(TipoServ.FindAll());
        }

        // GET: TipoInmobiliario/Details/5
        public ActionResult Details(int id)
        {
            return View(TipoServ.FindById(id));
        }

        // GET: TipoInmobiliario/Create
        public ActionResult Create()
        {
            ViewBag.TipoInmobiliario = TipoServ.FindAll();
            return View();
        }

        // POST: TipoInmobiliario/Create
        [HttpPost]
        public ActionResult Create(TipoInmobiliario collection)
        {
            ViewBag.Inmobiliario = inmobiliarioServ.FindAll();
            bool rpta = TipoServ.insert(collection);

            if (rpta)
            {
                return RedirectToAction("Index");
            }
                
                return View();
            
        }

        // GET: TipoInmobiliario/Edit/5
        public ActionResult Edit(int? id)  
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            

            TipoInmobiliario TipoI = TipoServ.FindById(id);

            return View(TipoI);
        }

        // POST: TipoInmobiliario/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, TipoInmobiliario collection)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            
            bool rpta = TipoServ.Update(collection);

            if (rpta)
            {
                return RedirectToAction("Index");
            }
            return View();
        }

        // GET: TipoInmobiliario/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            TipoInmobiliario TipoI = TipoServ.FindById(id);
            

            return View(TipoI);
        }

        // POST: TipoInmobiliario/Delete/5
        [HttpPost]
        public ActionResult Delete(TipoInmobiliario tp)
        {
            bool rpta = TipoServ.Delete(tp.TipoInmobiliarioId);

            if (rpta)
            {
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

WALimaRoomsV3.5-f82c69496623d605ed5b4bd9917f5774eca0c520/WALimaRoomsV3.5/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Lima Rooms</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Lima Rooms", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Tipo de Documentación", "Index", "TipoDocumento")</li>
                    <li>@Html.ActionLink("Cliente", "Index", "Cliente")</li>
                    <li>@Html.ActionLink("Tipo de Inmobiliario", "Index", "TipoInmobiliario")</li>
                    <li>@Html.ActionLink("Inmobiliario", "Index", "Inmobiliario")</li>
                    <li>@Html.ActionLink("Contrato", "Index", "Contrato")</li>
                    @*<li>@Html.ActionLink("Pago","Index","Pago")</li>*@




                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Lima Rooms. Todos los derechos reservados</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>